sudo: true
language: generic

matrix:
  include:
    - os: osx

before_install:
  - tools/travis/before_install.sh

install:
  - tools/travis/install.sh

script:
  - tools/travis/build.sh

cache:
  bundler: false
  directories:
    - dists/linux/prefix
